# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install dart dependencies
        run: dart pub get

      - uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.16.0

      - name: Install node dependencies
        run: npm install

      - name: Build the site
        run: ./dash_site build
        
      - name: Upload static files as artifact
        id: _site
        uses: actions/upload-pages-artifact@v3
        with:
          name: _site
          path: _site

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          # GitHub token
          token: ${{ github.token }}

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          # GitHub token
          token: ${{ github.token }}
          # Name of the artifact to deploy
          artifact_name: _site
          
